tls_server_config:
  cert_file: /home/{{ user }}/node_exporter.pem
  key_file: /home/{{ user }}/node_exporter.key
basic_auth_users:
  {{ pillar.prometheus_node_exporter.username }}: {{ pillar.prometheus_node_exporter.htpasswd }}
