global:
  scrape_interval: 60s
  scrape_timeout: 30s

scrape_configs:
  - job_name: 'prometheus-server-software'
    scrape_interval: 60s
    static_configs:
      - targets: ['localhost:9057']
    scheme: http
  - job_name: 'prometheus-server-node'
    scrape_interval: 60s
    static_configs:
      - targets: ['localhost:7231']
    scheme: http

  # Node Exporter.
{% for job_name, host in {
    'cove-live.oc4ids': 'ocp01.open-contracting.org',
    'live.docs': 'standard.open-contracting.org',
    'live.toucan': 'toucan.open-contracting.org',
    'live2.redash': 'redash.open-contracting.org',
    'live3.cove': 'ocp02.open-contracting.org',
    'kingfisher2': 'process1.kingfisher.open-contracting.org',
    'kingfisher-replica': 'replica1.kingfisher.open-contracting.org',
}.items() %}
  - job_name: 'ocds-{{ job_name }}'
    scrape_interval: 60s
    static_configs:
      - targets: ['{{ host }}:7231']
    scheme: https
    tls_config:
      ca_file: /home/{{ user }}/node_exporter.pem
    basic_auth:
      username: {{ pillar.prometheus_node_exporter.username }}
      password: {{ pillar.prometheus_node_exporter.password }}
{% endfor %}

  # The custom endpoint in Kingfisher Process, which adds new metrics prefixed by `kingfisher_process_`.
  - job_name: 'ocds-kingfisher2-process'
    scrape_interval: 300s
    metrics_path: /prometheus/metrics
    static_configs:
      - targets: ['process.kingfisher.open-contracting.org']
    scheme: http

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'localhost:9095'

rule_files:
  - /home/{{ user }}/conf-prometheus-rules.yml
