global:
  scrape_interval: 60s

scrape_configs:
  - job_name: 'prometheus-server-software'
    scrape_interval: 60s
    static_configs:
      - targets: ['localhost:9057']
    scheme: http
  - job_name: 'prometheus-server-node'
    scrape_interval: 60s
    static_configs:
      - targets: ['localhost:9157']
    scheme: http


alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'localhost:9095'

rule_files:
  - /home/{{ user }}/conf-prometheus-rules.yml

