name: Lint
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get install shellcheck
    - run: sudo snap install shfmt
    # https://github.com/koalaman/shellcheck/wiki/SC1071
    - run: shellcheck -e SC1071 $(shfmt -f .)
    - run: shfmt -d -i 4 -sr $(shfmt -f .)
